"""End-to-end test for ``run_generation`` with mixed source types.

Creates real PDF, text, and image files, mocks the URL fetcher and the
LangGraph pipeline, then calls ``run_generation`` with a ``fake`` provider.
Verifies that extraction branches correctly per source type and that the
pipeline result (sections, output path) is persisted.

Note: uses the project's file-based SQLite DB (via ``async_session``) with
cleanup after each test, rather than purely in-memory, because the global
engine is shared across the application.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import AsyncMock

import pytest

from app.db.database import async_session
from app.db.models import Project, ProjectStatus, ProviderConfig, Source

# ── helpers ────────────────────────────────────────────────────────────────


def _create_pdf(path: Path, text_lines: list[str]) -> None:
    """Write a single-page PDF with *text_lines* via PyMuPDF."""
    import fitz

    doc = fitz.open()
    page = doc.new_page()
    y = 72
    for i, line in enumerate(text_lines):
        page.insert_text((72, y + i * 24), line, fontsize=12)
    doc.save(str(path))
    doc.close()


def _create_image(path: Path, label: str = "Test Image") -> None:
    """Write a small PNG with text via Pillow."""
    from PIL import Image, ImageDraw

    img = Image.new("RGB", (200, 100), color="white")
    draw = ImageDraw.Draw(img)
    draw.text((20, 40), label, fill="black")
    img.save(str(path))


def _create_text_file(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


# ── synthetic pipeline result ──────────────────────────────────────────────


SYNTHETIC_LATEX = (
    r"\documentclass{article}"
    "\n"
    r"\begin{document}"
    "\n"
    r"\section{Introduction}"
    "\n"
    r"This is a test document generated by the fake provider."
    "\n"
    r"\end{document}"
    "\n"
)

FAKE_PIPELINE_RESULT = {
    "final_latex": SYNTHETIC_LATEX,
    "sections": [
        {
            "part_title": None,
            "title": "Introduction",
            "order_index": 0,
            "outline": None,
            "source_filenames": None,
            "latex": SYNTHETIC_LATEX,
        },
    ],
    "overview_latex": "",
    "references_pool": [],
    "bibliography_bib": "",
}


# ── test ───────────────────────────────────────────────────────────────────


@pytest.mark.asyncio
async def test_run_generation_mixed_sources(tmp_path, monkeypatch):
    """Run ``run_generation`` with PDF + text + image + URL sources.

    Uses a ``fake`` provider (no API calls) and mocks ``run_pipeline`` to
    skip LaTeX compilation. Verifies:
    * 4 documents are passed to the pipeline.
    * Each document has the correct keys and non-empty content.
    * Sections are persisted.
    * The project's ``output_tex_path`` is set.
    """
    # ── 1. Create real source files ────────────────────────────────────
    files_dir = tmp_path / "uploads"
    files_dir.mkdir()

    pdf_path = files_dir / "paper.pdf"
    _create_pdf(
        pdf_path,
        [
            "Machine Learning: A Comprehensive Overview",
            "This paper surveys supervised, unsupervised, and reinforcement",
            "learning paradigms.  We discuss key algorithms including SVMs,",
            "random forests, gradient boosting, and deep neural networks.",
        ],
    )

    text_path = files_dir / "notes.md"
    _create_text_file(
        text_path,
        (
            "# Deep Learning Notes\n\n"
            "Deep learning uses multi-layered neural networks to learn "
            "hierarchical representations.  Key architectures include CNNs "
            "for vision and transformers for NLP.\n\n"
            "## Training\n\n"
            "Gradient descent and backpropagation are the core training "
            "algorithms.\n"
        ),
    )

    img_path = files_dir / "diagram.png"
    _create_image(img_path, "Architecture Diagram")

    # ── 2. Set up database records ─────────────────────────────────────
    async with async_session() as session:
        provider = ProviderConfig(
            name="test-e2e-fake",
            provider_type="fake",
            default_model="fake-echo",
            is_active=True,
        )
        session.add(provider)
        await session.flush()

        project = Project(
            name="Test Mixed Sources",
            language="english",
            status=ProjectStatus.uploaded,
            total_sources=4,
        )
        session.add(project)
        await session.flush()

        sources = [
            Source(
                project_id=project.id,
                filename="paper.pdf",
                path=str(pdf_path),
                order_index=0,
                source_type="pdf",
            ),
            Source(
                project_id=project.id,
                filename="notes.md",
                path=str(text_path),
                order_index=1,
                source_type="text",
            ),
            Source(
                project_id=project.id,
                filename="diagram.png",
                path=str(img_path),
                order_index=2,
                source_type="image",
            ),
            Source(
                project_id=project.id,
                filename="example_com_page",
                path="https://example.com/article",
                order_index=3,
                source_type="url",
            ),
        ]
        for src in sources:
            session.add(src)
        await session.commit()

        project_id = project.id
        provider_id = provider.id

        # Ensure the figures directory exists (runner copies image sources
        # into ``figures_dir`` which is ``uploads/project_N/figures``).
        figures_dir = tmp_path / "uploads" / f"project_{project_id}" / "figures"
        figures_dir.mkdir(parents=True, exist_ok=True)

    # ── 3. Mock external dependencies ──────────────────────────────────
    # (a) WebSocket progress manager — consume events silently.
    monkeypatch.setattr(
        "app.services.runner.manager.emit",
        AsyncMock(),
    )

    # (b) URL fetcher — return synthetic content, no real HTTP.
    async def _fake_fetch(url: str, max_chars=None) -> str:
        return (
            "Transformer architectures have revolutionized natural language "
            "processing.  Models like BERT, GPT, and T5 achieve "
            "state-of-the-art results across benchmarks including GLUE, "
            "SuperGLUE, and SQuAD.  Recent advances in large language "
            "models have enabled zero-shot and few-shot learning."
        )

    monkeypatch.setattr(
        "app.services.runner.fetch_and_extract",
        _fake_fetch,
    )

    # (c) Pipeline — return synthetic result, capturing documents.
    captured_docs: list[dict] = []

    async def _fake_pipeline(documents=None, **kwargs):
        nonlocal captured_docs
        captured_docs = list(documents) if documents else []

        # Simulate progress callbacks.
        if "progress" in kwargs and kwargs["progress"]:
            cb = kwargs["progress"]
            await cb(
                {
                    "stage": "analyzing",
                    "message": "analysing (fake)",
                    "progress": 10,
                }
            )
            await cb(
                {
                    "stage": "writing",
                    "message": "writing (fake)",
                    "progress": 60,
                }
            )

        return dict(FAKE_PIPELINE_RESULT)

    monkeypatch.setattr(
        "app.services.runner.run_pipeline",
        _fake_pipeline,
    )

    # (d) Point uploads/output dirs at tmp_path.
    from app.core.config import settings

    monkeypatch.setattr(settings, "uploads_dir", tmp_path / "uploads")
    monkeypatch.setattr(settings, "output_dir", tmp_path / "output")

    # ── 4. Run generation ──────────────────────────────────────────────
    from app.services.runner import run_generation

    await run_generation(
        project_id=project_id,
        provider_id=provider_id,
        model="fake-echo",
    )

    # ── 5. Verify results ─────────────────────────────────────────────
    async with async_session() as session:
        project = await session.get(Project, project_id)
        assert project is not None

        assert project.status in (
            ProjectStatus.completed,
            ProjectStatus.failed,
        ), f"Unexpected status: {project.status}"

        assert project.output_tex_path, "output_tex_path not set"
        tex_path = Path(project.output_tex_path)
        assert tex_path.exists(), f"TeX file missing: {tex_path}"
        content = tex_path.read_text(encoding="utf-8")
        assert "begin{document}" in content

        assert project.total_sections >= 1, (
            f"Expected at least 1 section, got {project.total_sections}"
        )

    # ── 6. Verify documents extracted correctly ───────────────────────
    assert len(captured_docs) == 4, f"Expected 4 documents, got {len(captured_docs)}"

    required_keys = {"filename", "full_text", "figure_captions", "mandatory_figures"}

    # PDF
    pdf_doc = captured_docs[0]
    assert pdf_doc["filename"] == "paper.pdf"
    assert required_keys == set(pdf_doc.keys())
    assert len(pdf_doc["full_text"]) > 80, (
        f"PDF text too short: {len(pdf_doc['full_text'])} chars"
    )
    assert "Machine Learning" in pdf_doc["full_text"]

    # Text
    text_doc = captured_docs[1]
    assert text_doc["filename"] == "notes.md"
    assert required_keys == set(text_doc.keys())
    assert "Deep Learning" in text_doc["full_text"]
    assert "backpropagation" in text_doc["full_text"]

    # Image
    img_doc = captured_docs[2]
    assert img_doc["filename"] == "diagram.png"
    assert required_keys == set(img_doc.keys())
    assert len(img_doc["mandatory_figures"]) >= 1
    assert "figures/diagram.png" in img_doc["mandatory_figures"]
    assert len(img_doc["full_text"]) > 0

    # URL
    url_doc = captured_docs[3]
    assert url_doc["filename"] == "example_com_page"
    assert required_keys == set(url_doc.keys())
    assert "Transformer architectures" in url_doc["full_text"]

    # ── 7. Clean up database records ──────────────────────────────────
    async with async_session() as session:
        project = await session.get(Project, project_id)
        if project:
            await session.delete(project)
        provider = await session.get(ProviderConfig, provider_id)
        if provider:
            await session.delete(provider)
        await session.commit()
